spring:
  dubbo:
    application:
      name: channel-endpoint
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.meetcity.payment
logging:
  level:
    root: info
    com.meetcity: debug